fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    powershell: 'https://github.com/puppetlabs/puppetlabs-powershell.git'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.13.0
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    mount_iso: "#{source_dir}"
